var car = "Toyota Corolla";
console.log("Is car == 'Toyota Corolla'? I predict true");
console.log(car == "Toyota Corolla");
console.log("Is car == 'toyota corolla'? I predict false");
console.log(car == "toyota corolla");
var Bike = "Kawasaki Ninja";
console.log("Is Bike == 'Kawasaki Ninja'? I predict true");
console.log(Bike == "Kawasaki Ninja");
console.log("Is Bike == 'Hayabusa'? I predict false");
console.log(Bike == "Hayabusa");
var laptop = "Surface Pro 3";
console.log("Is laptop == 'Surface Pro 3'? I predict true");
console.log(laptop == "Surface Pro 3");
console.log("Is laptop == 'MacBook Pro'? I predict false");
console.log(laptop == "MacBook Pro");
var browser = "Microsoft Edge";
console.log("Is browser == 'Microsoft Edge'? I predict true");
console.log(browser == "Microsoft Edge");
console.log("Is browser == 'Google Chrome'? I predict false");
console.log(browser == "Google Chrome");
var country = "Pakistan";
console.log("Is country == 'Pakistan'? I predict true");
console.log(country == "Pakistan");
console.log("Is country == 'pakistan'? I predict false because javascript is case sensitive");
console.log(country == "pakistan");
var city = "Karachi";
console.log("Is city == 'Karachi'? I predict true");
console.log(city == "Karachi");
console.log("Is city == 'ka rachi'? I predict false");
console.log(city == "ka rachi");
